// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/projects/[slug]" | "/projects/[slug]/prompts" | "/projects/[slug]/storyboard" | "/projects/[slug]/tasks/[taskId]"
type AppRouteHandlerRoutes = "/api/health" | "/api/projects/[slug]/assets/[fileName]" | "/api/projects/[slug]/prompts" | "/api/projects/[slug]/storyboard" | "/api/projects/[slug]/tasks" | "/api/projects/[slug]/tasks/[taskId]" | "/api/projects/[slug]/tasks/[taskId]/result" | "/api/projects/[slug]/tasks/[taskId]/retry" | "/api/projects/[slug]/tasks/[taskId]/sync" | "/api/projects/[slug]/tasks/submit" | "/api/projects/demo" | "/api/projects/import"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/health": {}
  "/api/projects/[slug]/assets/[fileName]": { "slug": string; "fileName": string; }
  "/api/projects/[slug]/prompts": { "slug": string; }
  "/api/projects/[slug]/storyboard": { "slug": string; }
  "/api/projects/[slug]/tasks": { "slug": string; }
  "/api/projects/[slug]/tasks/[taskId]": { "slug": string; "taskId": string; }
  "/api/projects/[slug]/tasks/[taskId]/result": { "slug": string; "taskId": string; }
  "/api/projects/[slug]/tasks/[taskId]/retry": { "slug": string; "taskId": string; }
  "/api/projects/[slug]/tasks/[taskId]/sync": { "slug": string; "taskId": string; }
  "/api/projects/[slug]/tasks/submit": { "slug": string; }
  "/api/projects/demo": {}
  "/api/projects/import": {}
  "/projects/[slug]": { "slug": string; }
  "/projects/[slug]/prompts": { "slug": string; }
  "/projects/[slug]/storyboard": { "slug": string; }
  "/projects/[slug]/tasks/[taskId]": { "slug": string; "taskId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
