// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]">> = Specific
  const handler = {} as typeof import("../../app/projects/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[slug]/prompts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]/prompts">> = Specific
  const handler = {} as typeof import("../../app/projects/[slug]/prompts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[slug]/storyboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]/storyboard">> = Specific
  const handler = {} as typeof import("../../app/projects/[slug]/storyboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/[slug]/tasks/[taskId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[slug]/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../app/projects/[slug]/tasks/[taskId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/assets/[fileName]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/assets/[fileName]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/assets/[fileName]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/prompts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/prompts">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/prompts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/storyboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/storyboard">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/storyboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/tasks/[taskId]/result/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/tasks/[taskId]/result">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/tasks/[taskId]/result/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/tasks/[taskId]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/tasks/[taskId]/retry">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/tasks/[taskId]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/tasks/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/tasks/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/tasks/[taskId]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/tasks/[taskId]/sync">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/tasks/[taskId]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[slug]/tasks/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[slug]/tasks/submit">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[slug]/tasks/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/demo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/demo">> = Specific
  const handler = {} as typeof import("../../app/api/projects/demo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/import">> = Specific
  const handler = {} as typeof import("../../app/api/projects/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
